<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "specialitylocal"
 *
 * Auto generated by Extension Builder 2014-02-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Customize Speciality Local',
	'description' => 'Customizes the EXT:speciality with stuffs specific of this website.',
	'category' => 'misc',
	'author' => 'Ian Excedo',
	'author_email' => 'ian@webian.it',
	'author_company' => 'webian.it',
	'shy' => '',
	'priority' => 'top',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>